VERTICAL=false
X=instance_exists(battle_board) ? battle_board.x : 320
Y=instance_exists(battle_board) ? battle_board.y : 320
HSPEED=0
VSPEED=0
TYPE=0
ROTATE=0
GAP_POS=0
GAP_SIZE=20
DESTROY=0
PAPS=0
DURATION=-1
FOLLOW=false
FOLLOW_BOARD=false
FOLLOW_TARGET=noone
FOLLOW_ANGLE=noone
FOLLOW_X=noone
FOLLOW_Y=noone
bones = []